name: Agave Cargo.toml Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # Check every 5 minutes
  workflow_dispatch:

jobs:
  monitor-agave:
    runs-on: ubuntu-latest
    steps:
      - name: Check Agave commits
        id: check-commits
        run: |
          # Get latest commits from agave repo
          COMMITS=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/farawaystar/solana-core/commits?per_page=15")


          # Track processed commits
          LAST_PROCESSED=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \

            jq -r '.artifacts[0].name // empty' | cut -d'-' -f3)
          # Check for Cargo.toml modifications
          echo "$COMMITS" | jq -r '.[].sha' | while read SHA; do
            if [[ -n "$LAST_PROCESSED" && "$SHA" == "$LAST_PROCESSED" ]]; then
              break
            fi

            FILES=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
              "https://api.github.com/repos/farawaystar/solana-core/commits/$SHA" | \
              jq -r '.files[].filename')
              
            if echo "$FILES" | grep -q 'Cargo.toml'; then
              echo "Detected Cargo.toml change in commit $SHA"
              echo "changed_commit=$SHA" >> $GITHUB_OUTPUT
              break
            fi
          done
      - name: Error logging
        if: ${{ failure() }}
        run: |
          echo "::error:: Failed to process SHA: $SHA"
          echo "Failed SHA: $SHA" >> errors.log
          echo "API Response:" >> debug.log
          curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/rust-lang/agave/commits/$SHA" >> debug.log
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT" >> debug.log
        env:
          SHA: ${{ steps.check-commits.outputs.changed_commit }}

      - name: Trigger artifact generation
        if: steps.check-commits.outputs.changed_commit
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'process-cargo-changes.yml',
              ref: 'master',
              inputs: {
                commit_sha: '${{ steps.check-commits.outputs.changed_commit }}'
              }
            })
