name: Agave Cargo.toml Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # Check every 5 minutes
  workflow_dispatch:

jobs:
  monitor-agave:
    runs-on: ubuntu-latest
    steps:
      - name: Check Agave commits
        id: check-commits
        run: |
          # Get latest commits from agave repo
          COMMITS=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/farawaystar/agave-monitor/commits?per_page=10")

          # Check for Cargo.toml modifications
          echo "$COMMITS" | jq -r '.[].sha' | while read SHA; do
            FILES=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
              "https://api.github.com/repos/farawaystar/agave-monitor/commits/$SHA" \
              | jq -r '.files[].filename')
              
            if echo "$FILES" | grep -q 'Cargo.toml'; then
              echo "Detected Cargo.toml change in commit $SHA"
              echo "changed_commit=$SHA" >> $GITHUB_OUTPUT
              break
            fi
          done

      - name: Trigger artifact generation
        if: steps.check-commits.outputs.changed_commit
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'process-cargo-changes.yml',
              ref: 'main',
              inputs: {
                commit_sha: '${{ steps.check-commits.outputs.changed_commit }}'
              }
            })
