name: Agave Cargo.toml Monitor

on:
  workflow_dispatch:

jobs:
  monitor-agave:
    runs-on: ubuntu-latest
    steps:
      - name: Check Agave commits
        id: check-commits
        run: |
          # Get latest commits from agave repo
          COMMITS=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/farawaystar/solana-core/commits?per_page=15")


          # Track processed commits
          LAST_PROCESSED=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=workflow_dispatch&status=completed&per_page=1&sort=created&direction=desc" | \
            jq -r '.workflow_runs[0].inputs.commit_sha // empty')

          # Check for Cargo.toml modifications
          echo "$COMMITS" | jq -r '.[].sha' | while read SHA; do
            [[ "$SHA" == "$LAST_PROCESSED" ]] && break

            FILES=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
              "https://api.github.com/repos/farawaystar/solana-core/commits/$SHA" | \
              jq -r '.files[].filename')
              
            grep -q 'Cargo\.toml$' <<< "$FILES" && {
              echo "changed_commit=$SHA" >> $GITHUB_OUTPUT
              echo "Found in $SHA" >&2
            }
          done

      - name: Error logging
        if: ${{ failure() }}
        run: |
          echo "::error:: Failed to process SHA: $SHA"
          echo "Failed SHA: $SHA" >> errors.log
          echo "API Response:" >> debug.log
          curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/rust-lang/agave/commits/$SHA" >> debug.log
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT" >> debug.log
        env:
          SHA: ${{ steps.check-commits.outputs.changed_commit }}

      - name: Trigger artifact generation
        if: steps.check-commits.outputs.changed_commit
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'process-cargo-changes.yml',
              ref: 'master',
              inputs: {
                commit_sha: '${{ steps.check-commits.outputs.changed_commit }}'
              }
            })
